FROM ubuntu:16.04

LABEL maintainer="Jason Zaman <jason@perfinion.com>"

# Copy and run the install scripts.
COPY install/*.sh /install/

RUN /install/install_deb_packages.sh
RUN /install/install_pip_packages.sh
RUN /install/install_bazel.sh
RUN /install/install_proto3.sh
RUN /install/install_buildifier.sh
RUN /install/install_golang.sh

# Set up the master bazelrc configuration file.
COPY install/bazelrc /etc/bazel.bazelrc
