     OCTOPUS_PROJECT: update to the name of your Octopus project
      OCTOPUS_ENVIRONMENT: 100%
      Subject: [PATCH] Fix summary generator and disable clang

Welcome to Code Sight
Get ready to start using Black Duck® Code Sight™ to find and fix security and quality issues in your code, as you code. We will help you detect vulnerabilities in your source code and your open source dependencies, and help you fix them quickly with guidance written and curated by Black Duck cybersecurity experts.

Code Sight supports the following Black Duck products:

Polaris Software Integrity Platform®
Coverity® SAST
Black Duck® SCA
Software Risk Manager
Code Sight Standard Edition (Free trial available)
Let's Get Started:
To begin, navigate to the “Status” tab and click into the “Products and Licenses” section to activate Code Sight. Then:

Not a Black Duck customer?	Black Duck customer?
Sign up for a free trial of the standalone Code Sight plugin, allowing you to run rapid scans of source code and open source in only a couple of minutes.	Activate your Black Duck product whether you are using the standalone plugin or extending the enterprise functionality of other supported Black Duck tools.
Supported Developer Workflows:
Code Sight supports the following developer workflows:

Local View: Scan in the IDE to find vulnerabilities specific to the code changes you made locally.
Team View: View issues found during centralized, pipeline-based scans and persisted on a Black Duck server.
Visit our documentation to get more details on how to use Code Sight and activate your license.

Guided Walkthroughs:
Check out these quick guided walkthroughs that will help you get started:

 Polaris Quick Tour
 Coverity Quick Tour
 Black Duck SCA Quick Tour
 Code Sight Standard Edition Quick Tour
Click here to request the software bill of materials (SBOM) for Black Duck Code Sight. For more information, visit Executive Order on Improving the Nation's Cybersecurity.
Index: tf_sig_build_dockerfiles/devel.usertools/code_check_changed_files.bats
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tf_sig_build_dockerfiles/devel.usertools/code_check_changed_files.bats b/tf_sig_build_dockerfiles/devel.usertools/code_check_changed_files.bats
deleted file mode 100644
--- a/tf_sig_build_dockerfiles/devel.usertools/code_check_changed_files.bats	(revision 2a30e896bf580ad47a8fb21bf69cc89347581ffe)
+++ /dev/null	(revision 2a30e896bf580ad47a8fb21bf69cc89347581ffe)
@@ -1,56 +0,0 @@
-# vim: filetype=bash
-# This file is a work in progress, designed to replace the complicated test
-# orchestration previously placed in TensorFlow's ci_sanity.sh.
-# This is not currently in use.
-setup_file() {
-    cd /tf/tensorflow
-    bazel version  # Start the bazel server
-    # Note that you could generate a list of all the affected targets with e.g.:
-    # bazel query $(paste -sd "+" $BATS_FILE_TMPDIR/changed_files) --keep_going
-    # This assumes that origin/master will always be the correct base branch
-    # comparison... maybe this could be optionally passed in from GitHub Actions
-    # Only shows Added, Changed, Modified, Renamed, and Type-changed files
-    git diff --diff-filter ACMRT --name-only origin/master > $BATS_FILE_TMPDIR/changed_files
-}
-
-# Note: this is excluded on the full code base, since any submitted code must
-# have passed Google's internal style guidelines.
-@test "Check buildifier formatting on BUILD files" {
-    echo "buildifier formatting is recommended. Here are the suggested fixes:"
-    echo "============================="
-    grep -e 'BUILD' $BATS_FILE_TMPDIR/changed_files \
-        | xargs buildifier -v -mode=diff -diff_command="git diff --no-index"
-}
-
-# Note: this is excluded on the full code base, since any submitted code must
-# have passed Google's internal style guidelines.
-@test "Check formatting for C++ files" {
-    skip "clang-format in OSS doesn't match Google-internal, and reports too much."
-    echo "clang-format is recommended. Here are the suggested changes:"
-    echo "============================="
-    grep -e '\.h$' -e '\.cc$' $BATS_FILE_TMPDIR/changed_files > $BATS_TEST_TMPDIR/files || true
-    if [[ ! -s $BATS_TEST_TMPDIR/files ]]; then return 0; fi
-    xargs -a $BATS_TEST_TMPDIR/files -i -n1 -P $(nproc --all) \
-        bash -c 'clang-format-12 --style=Google {} | git diff --no-index {} -' \
-        | tee $BATS_TEST_TMPDIR/needs_help.txt
-    echo "You can use clang-format --style=Google -i <file> to apply changes to a file."
-    [[ ! -s $BATS_TEST_TMPDIR/needs_help.txt ]]
-}
-
-# Note: this is excluded on the full code base, since any submitted code must
-# have passed Google's internal style guidelines.
-@test "Check pylint for Python files" {
-    echo "Python formatting is recommended. Here are the pylint errors:"
-    echo "============================="
-    grep -e "\.py$" $BATS_FILE_TMPDIR/changed_files > $BATS_TEST_TMPDIR/files || true
-    if [[ ! -s $BATS_TEST_TMPDIR/files ]]; then return 0; fi
-    xargs -a $BATS_TEST_TMPDIR/files -n1 -P $(nproc --all) \
-        python -m pylint --rcfile=tensorflow/tools/ci_build/pylintrc --score false \
-        | grep -v "**** Module" \
-        | tee $BATS_TEST_TMPDIR/needs_help.txt
-    [[ ! -s $BATS_TEST_TMPDIR/needs_help.txt ]]
-}
-
-teardown_file() {
-    bazel shutdown
-}
Index: tf_sig_build_dockerfiles/devel.usertools/save_summary_xml.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tf_sig_build_dockerfiles/devel.usertools/save_summary_xml.sh b/tf_sig_build_dockerfiles/devel.usertools/save_summary_xml.sh
--- a/tf_sig_build_dockerfiles/devel.usertools/save_summary_xml.sh	(revision 2a30e896bf580ad47a8fb21bf69cc89347581ffe)
+++ b/tf_sig_build_dockerfiles/devel.usertools/save_summary_xml.sh	(revision 7a83818bbded7bee0ba0dc091ed0e7c9380cb5ac)
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-# Usage: save_summary_xml.sh OUTPUT BAZEL_TEST_COMMAND...
+# Usage: save_summary.sh OUTPUT BAZEL_TEST_COMMAND...
 OUTPUT=$1
 shift
 mkdir -p "$(dirname $OUTPUT)"
-"$@" 2>&1 | tee "$OUTPUT.txt"
-python /usertools/save_summary_xml.py $OUTPUT.txt $OUTPUT
+"$@" 2>&1 | tee $OUTPUT.txt
+/usertools/save_summary_xml.sh $OUTPUT.txt $OUTPUT
 rm $OUTPUT.txt

name: 'Build and Deploy to Octopus Deploy'

on:
  push:
    branches:
      - '"r3.0"'

jobs:
  build:
    name: Build
    runs-on: Windows 10
    permissions:
      packages: write
      contents: read
    env:
      DOCKER_REGISTRY: ghcr.io                                # TODO: Update to your docker registry uri
      DOCKER_REGISTRY_USERNAME: ${{ github.actor }}           # TODO: Update to your docker registry username
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}   # TODO: Update to your docker registry password
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ env.DOCKER_REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}
          tags: type=semver,pattern={{version}},value=v1.0.0-{{sha}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy
    permissions:
      id-token: write
    runs-on: Windows 10
    needs: [ build ]
    env:
      OCTOPUS_URL: 'https://your-octopus-url'             # TODO: update to your Octopus Instance url
      OCTOPUS_SERVICE_ACCOUNT: 'your-service-account-id'  # TODO: update to your service account Id
      OCTOPUS_SPACE: 'your-space'                         # TODO: update to the name of the space your project is configured in
      OCTOPUS_PROJECT: 'your-project'                     # TODO: update to the name of your Octopus project
      OCTOPUS_ENVIRONMENT: 'your-environment'             # TODO: update to the name of the environment to recieve the first deployment

    steps:
      - name: Log in to Octopus Deploy
        uses: OctopusDeploy/login@34b6dcc1e86fa373c14e6a28c5507d221e4de629  #v1.0.2
        with:
          server: '${{ env.OCTOPUS_URL }}'
          service_account_id: '${{ env.OCTOPUS_SERVICE_ACCOUNT }}'

      - name: Create Release
        id: create_release
        uses: OctopusDeploy/create-release-action@fea7e7b45c38c021b6bc5a14bd7eaa2ed5269214 #v3.2.2
        with:
          project: '${{ env.OCTOPUS_PROJECT }}'
          space: '${{ env.OCTOPUS_SPACE }}'
          packages: '*:${{ needs.build.outputs.image_tag }}'

      - name: Deploy Release
        uses: OctopusDeploy/deploy-release-action@b10a606c903b0a5bce24102af9d066638ab429ac #v3.2.1
        with:
          project: '${{ env.OCTOPUS_PROJECT }}'
          space: '${{ env.OCTOPUS_SPACE }}'
          release_number: '${{ steps.create_release.outputs.release_number  }}'
          environments: ${{ env.OCTOPUS_ENVIRONMENT }}
